### ISSUE TITLE
[refactor]: 전전날의 투표 결과를 확인하라는 알림을 disable 시킨다.

### ISSUE THREAD

**Issue by kpeel5839** [YAPP-Github/24th-App-Team-1-BE#113]
### Epic/Story Ticket Number

None

### 작업 사항

전전날의 투표 결과를 확인하라는 알림을 disable 시키고, disable 시키면 사용자가 read 한 것으로 대체한다.

### Todo

- [x] 전전날의 투표 결과를 확인하라는 알림 disable 시키기
- [x] disable 시킨 알림은 read 한 것으로 대체
- [x] 테스트 추가 및 수정
