### ISSUE TITLE
[feature]: 유저는 알림 설정을 수정할 수 있다

### ISSUE THREAD

**Issue by kpeel5839** [YAPP-Github/24th-App-Team-1-BE#48]
### Epic/Story Ticket Number

WS-161

### 작업 사항

유저가 알림 설정을 변경할 수 있도록 기능을 추가할 것입니다. (투표, 쪽지 따로)
이에 따라 알림 로직도 수정할 예정입니다. (컬럼 추가 후)

### Todo

- [x] 유저 알림 설정 변경 기능 추가 (투표, 쪽지 알림 설정 따로 추가)
- [x] 알림 수정 (테스트 추가, 투표 및 쪽지에 따라 알림 발생하게끔)
- [x] 테스트 추가 (알림 설정 변경 기능, 알림 기능)
